# Generated by Django 3.1 on 2022-04-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_staf',
            new_name='is_staff',
        ),
    ]
